name: Build and Publish CPU Docker Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Show Working Directory (Optional)
        run: |
            pwd
            ls -la
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.cpu
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/removebg_infusiblecoder:latest
          context: .
          platforms: linux/amd64,linux/arm64
          secrets: |
            OCKER_HUB_USERNAME
            DOCKER_HUB_ACCESS_TOKEN
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/removebg_infusiblecoder:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/removebg_infusiblecoder:buildcache,mode=max  
